### ISSUE TITLE
cannot add validator due to prefix error

### ISSUE THREAD

**Issue by noot** [aragon/aragon-chain#18]
instructions:
```
make install
aragonchaind tendermint show-validator 
```
use public key as `--pubkey` in the following:

```
$ aragonchaincli tx staking create-validator --amount 100000000000000ara --pubkey aragonvalconspub1zcjduepqmtrd6qlxjf6ce5vd7ath358vcfamjl6hy00c5l5lwss9r4uxeesqc5ydw4 --moniker noot --chain-id=127001 --commission-rate="0.10" --commission-max-rate="0.20" --commission-max-change-rate="0.01" --min-self-delegation="1" --gas="auto" --from mykey
ERROR: failed to unmarshal JSON bytes: invalid Bech32 prefix; expected eth, got aragon
```

it should not be expecting an eth-prefixed key

**Comment by fedekunze** [comment]
hmmm there should be a config error somewhere

**Comment by araskachoi** [comment]
was able to get this to work using these instructions:

Using this dockerfile:
```
FROM golang:1.14
RUN apt-get update && apt-get install -y \
make curl jq tmux vim
COPY . $HOME/aragon-chain
WORKDIR $HOME/aragon-chain
RUN make install
EXPOSE 26656 26657 1317 8545 8546
ENTRYPOINT ["/bin/bash"]
```

1. start network on node0
```
# node0
./init.sh
```
2. copy over genesis file from node0 to node1
```
# host machine (if on docker - use scp otherwise)
docker cp <node0_container_id>:/root/.aragonchaind/config/genesis.json ./
docker cp ./genesis.json <node1_container_id>:/root/.aragonchaind/config/genesis.json
```
- note: may need to do `mkdir ...` to create that directory as it might not exist yet

3. get node ID of node0
```
#node0
aragonchaind tendermint show-node-id
```
- need to take the output of this and add to next step

4. add persistent peer
```
#node1
vim ~/.aragonchaind/config/config.toml
```
- if you dont have vim, run apt-get install -y vim
- find where persistent_peers is located and add the nodeID along with ip + port
  - ex.) persistent_peers = "eec60f86a6c36bc9e1662f29fbc6745ea4b76525@172.17.0.4:26656"

5. have node1 join the network
```
#node1
aragonchaind start --pruning=nothing --rpc.unsafe --log_level "main:info,state:info,mempool:info" --trace > aragonchaind.log &
```
- try doing tail aragonchaind.log to make sure the node is syncing!

6. get chain_id of network
```
# either on node0 or node1
cat ~/.aragonchaind/config/genesis.json | grep chain_id
```
- need to replace the chainID in step 6. with the output

7. add new acct on node1
```
#node1
aragonchaincli config keyring-backend test
aragonchaincli keys add qq
```
- copy the address of qq and use in next step
  - this can also be done using aragonchaincli keys show qq -a

8. send funds to qq
```
#node0
aragonchaincli tx send mykey <node1_ara_address> 100000000000001ara
```

9. add node1 as a validator
```
#node1
aragonchaincli tx staking create-validator --amount 100000000000000ara --pubkey $(aragonchaind tendermint show-validator) --moniker noot --chain-id=<REPLACE_CHAIN_ID> --commission-rate="0.10" --commission-max-rate="0.20" --commission-max-change-rate="0.01" --min-self-delegation="1" --gas="auto" --from qq
```
