### ISSUE TITLE
Docs: link to Aragon Forum's Chain category

### ISSUE THREAD

**Issue by izqui** [aragon/aragon-chain#8]
https://forum.aragon.org/c/aragon-chain

<img width="390" alt="image" src="https://user-images.githubusercontent.com/447328/91464337-c23c0400-e88c-11ea-8a3c-286bfc657392.png">

**Comment by fedekunze** [comment]
do you have a logo to replace the ethermint one?

**Comment by izqui** [comment]
@john-light @owisixseven what should we use here?

**Comment by john-light** [comment]
Aragon Chain logo should work
